name: crystal_cascade
description: Crystal Cascade - Premium Hybrid Casual Puzzle Game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.1.0
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  confetti: ^0.8.0
  shimmer: ^3.0.0
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/